Feature/login checkbox
mathsemilio/desafio-beca-android-luciana pull request #6
Opened 2021-09-26 15:48 UTC by LucianaCabral

2021-09-26 15:53 UTC, LucianaCabral commented
Matheus, certamente vão ter alguns conflitos, porque modifiquei o xml, para adequar ao checkbox e otimizei toast.

2021-09-26 16:21 UTC, LucianaCabral commented
Matheus, resolvi os conflitos que foram algumas modificações no projeto. A chamada do método para o checkbox não está setada na classe. Como já fiz o PR, Irei fazer esta modificação assim que vc fechar o PR. Valeu!!!

2021-09-27 23:35 UTC, mathsemilio commented on app/src/main/java/com/github/mathsemilio/desafiobecaluciana/extensions/ViewExtensions.kt
> +fun Fragment.toast(string: String) {
Esta função seria melhor chamada de `showToast`. Lembre-se, os nomes das funções devem sempre dar idéia de ação.

2021-09-27 23:42 UTC, mathsemilio commented on app/src/main/res/values/colors.xml
> +    <color name="trasnparente">@android:color/transparent</color>
Tente sempre usar um padrão ao nomear recursos, neste caso o melhor nome para essa color resource seria `colorTransparent`. Mesmo assim, como o Android já possui uma definição para a "cor" transparente, é melhor usar ela e remover essa color resource.

2021-09-27 23:49 UTC, mathsemilio commented on app/src/main/res/values/strings.xml
> +    <string name="cancel">Cancel</string>
O mesmo vale para as String resources, tente criar um padrão para que você não precise ficar olhando no arquivo `strings.xml`  para ver o que uma string significa. Por exemplo, essa string `cancel`, ela é somente usada como um texto para um botão de diálogo. Então seria melhor renomea-lá para algo como `dialog_button_cancel`. Outro exemplo, a string `login_success` poderia ser renomeada para `message_login_success`, até porque ela só utilizado como mensagem (em forma de Toast) para o usuário. Desta forma você tem uma hierarquia de strings e fica fácil descobrir o seu propósito.

2021-09-27 23:52 UTC, mathsemilio requested changes
Apontei algumas coisas sobre estilo de código, mas analisando o código eu vi que a implementação do checkbox não está completa. É necessária que a feature esteja completa para a aprovação do PR.

2021-09-29 15:13 UTC, closed without merging